src/reports/modified-lar/index.jsx

add link to modified lar spec

---

src/reports/Report.jsx
src/reports/tables/Five.jsx
src/reports/tables/Four.jsx
src/reports/tables/index.jsx

Implement 4-* series of tables

---

src/reports/MsaMds.jsx
src/reports/Reports.jsx

set heading correctly for aggregate reports

---

src/reports/Report.jsx
src/reports/tables/TwelveOne.jsx
src/reports/tables/index.jsx

implement table 12-1

---

src/reports/Report.jsx
src/reports/tables/B.jsx
src/reports/tables/TwelveOne.jsx
src/reports/tables/index.jsx

Depends on #81 
Closes #41 
Closes #43

Report B and BW

---

src/constants/disclosure-reports.js

See cfpb/hmda-platform#1286 and cfpb/hmda-platform#1289

Remove unneeded supplemental tables from disclosure list

---

src/Option.js
src/reports/Selector.jsx
src/reports/tables/Eleven.jsx
src/reports/tables/Five.jsx
src/reports/tables/Four.jsx
src/reports/tables/TwelveTwo.jsx
yarn.lock

Fixup keys

---

src/reports/tables/tables.scss

Add overflow-x to table wrapper

---

src/constants/aggregate-reports.js

Remove Table 10

---

src/app.scss
src/reports/Selector.jsx
src/sass/select-fix.scss

Quite nice for when hundreds of MSA options exist

Select css fixes to allow searchable option

---

src/reports/aggregate/index.jsx
src/reports/disclosure/Disclosure.scss
src/reports/disclosure/Results.jsx
src/reports/disclosure/index.jsx

Gray out loading

---

src/App.jsx
src/Home.jsx
src/reports/modified-lar/index.jsx
src/reports/snapshot/index.jsx

National dataset

---

src/reports/modified-lar/index.jsx

Fix link to 2017 spec

---

src/reports/tables/I.jsx

Simplify Table i header

---

src/constants/aggregate-reports.js
src/constants/disclosure-reports.js
src/reports/tables/Eight.jsx

add 8-5 to constants tables

---

src/reports/tables/One.jsx

show message for no data

---

src/reports/Report.jsx
src/reports/tables/A4.jsx
src/reports/tables/index.jsx

Add A4 table

---

src/reports/tables/TwelveTwo.jsx

remove extraneous column

---

src/constants/aggregate-reports.js
src/constants/disclosure-reports.js

Closes #150 
I blame a permissive find and replace on switching from id -> value ;)

fix incidence typo

---

src/reports/tables/TwelveTwo.jsx

don't render the HOEPA loans data

---

src/App.jsx
src/Home.jsx
src/common/NotFound.jsx

Closes #134 
Closes #141 
- updates homepage with correct links and "coming soon" labels 
- only aggregate should work
- updates routes to do the same
- makes small improvements to the "not found" page

Release updates

---

src/reports/ModifiedLar.jsx

fix link to modified lar spec

---

src/App.jsx
src/Home.jsx
src/reports/Report.jsx

Updates to allow for the release of the disclosure reports.
Also closes #136

WIP - Disclosure

---

src/reports/Selector.jsx
src/reports/Selector.scss

custom error message for react-select-plus to match other error messages

---

src/App.jsx
src/Home.jsx
src/constants/national-aggregate-reports.js
src/reports/NationalAggregate.jsx
src/reports/Report.jsx
src/reports/Reports.jsx

Sets everything up for the release of the national aggregate reports. For more details ...
Closes #176 
Closes #177 
Closes #178 
Closes #179 
Closes #180

National aggregate reports

---

src/App.jsx
src/Home.jsx
src/reports/DynamicDataset.jsx
src/reports/snapshot/index.jsx

Dynamic TS and LAR datasets

---

src/constants/disclosure-reports.js

Closes #149 - Report BW (from [this comment](https://github.com/cfpb/hmda-pub-ui/issues/149#issuecomment-407873975)) was [already listed](https://github.com/cfpb/hmda-pub-ui/pull/187/files#diff-3b715c0eb15604431f4bb1b554327d85R239).

WIP - adds A4 and A4W disclosure reports

---

src/reports/DynamicDataset.jsx

update dynamic dataset intro

---

nginx/nginx.conf

Along with
- https://github.com/cfpb/hmda-platform-tools/pull/175 and
- https://github.com/cfpb/hmda-homepage/pull/44
Closes #203

fix refresh when at /data-publication/something-else

---

src/reports/Results.jsx
src/reports/SearchList.css
src/reports/SearchList.jsx

fix styling of input error message

---

src/Header.jsx

Depends on cfpb/hmda-platform-ui#1189

update link to point to 2018 UI

---

src/Footer.jsx
src/app.css
src/reports/Disclosure.jsx
src/reports/tables/Nine.jsx

Cra warning cleanup

---

src/Header.css
src/Header.jsx

Add breakpoint and display logotext as span

---

src/reports/Results.jsx

Fix institutions typo

---

src/Home.css
src/Home.jsx

update flex cards on homepage

---

src/reports/Report.jsx
src/reports/tables/index.jsx

addresses issue : [275](https://github.com/cfpb/hmda-pub-ui/issues/275)
Looks like we just needed to add references to the rest of the reports for them to show up properly.

enable aggregate tables [deploy pr]

---

src/reports/Report.css
src/reports/Report.jsx
src/reports/tables/Aggregate3.jsx
src/reports/tables/Aggregate4.jsx
src/reports/tables/Aggregate5.jsx

Resolves issues : 
[274](https://github.com/cfpb/hmda-pub-ui/issues/274)
[275](https://github.com/cfpb/hmda-pub-ui/issues/275)
[265](https://github.com/cfpb/hmda-pub-ui/issues/265)

2019 report wire up

---

src/reports/snapshot/index.jsx

switch spec links to pdf

---

src/reports/Disclosure.jsx
src/reports/MsaMds.jsx
src/reports/fetchMsas.js

handle errors for fetchMsas

---

src/App.jsx
src/common/YearSelector.jsx
src/constants/dynamic-dataset.js
src/constants/snapshot-dataset.js
src/reports/DynamicDataset.jsx
src/reports/snapshot/index.jsx

added multi year ui

---

src/reports/Results.jsx
src/reports/SearchList.jsx

Allow search by lei/institution id and update labels to point this out

---

src/reports/SearchList.jsx
src/reports/fetchMsas.js

hardcode prod filers endpoint

---

src/reports/Report.jsx

switch aggregate reports to prod bucket

---

src/constants/snapshot-dataset.js
src/reports/snapshot/index.jsx

add format/code sheet & update snapshot per year content

---

src/reports/Disclosure.jsx

update respondent id label to institution id
